project:
  type: website

website:
  title: "Saving Derna"
  navbar:
    backgroud: primary
    search: true
    left:
      - dataPrep.qmd
      - Report.qmd
      - analysis.qmd
      - results.qmd
      - learned.qmd
      - poster.qmd
    right: 
      - href: index.qmd
        text: Home
      - about.qmd
      
      
format:
  html:
    theme: 
      dark: darkly
      light: yeti
    css: styles.css
    toc: true

editor: visual


