project:
  type: website

website:
  title: "smt201gis-t3"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - Report.qmd
      - analysis.qmd
      - results.qmd
      - learned.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

