# **Lessons learnt**

From this project, we learned that it is important to consider scale when determining our scope of investigation. Despite Derna being a small city, it seemed that the 250m hexagon map was sufficient to cover our study area and reflect the trends of population density and accessibility that we investigated. However, as mentioned in our future considerations, our analysis could have benefitted from a more precise map using smaller hexagon sizes as our features of focus within Derna were also smaller and more densely packed than we anticipated.

Furthermore, as Derna\'s datasets were not extensive nor fully-detailed, we had to learn how to make best-guess estimates and manually clean the data using our knowledge on-hand about Derna. For example, since Derna didn\'t have official data on its population density across the city, we decided to use residential buildings as an estimate of where people would be. As mentioned above, we also had to make informed guesses and reference satellite data when determining which unclassified building polygons were actually residential buildings. Though these may yield less accurate findings, making these informed estimations based on existing data allowed us to observe and map the trends of residents\' accessibility to evacuation centres.

Lastly, we recognised the importance of GIS technology in providing the government and external humanitarian aid services an analytical view of Derna for flood mitigation measures. The areas we identified as being poor in accessibility to both evacuation centres and healthcare facilities could be prioritised, better focusing humanitarian aid efforts to create more efficient processes for post-flood mitigation. Visualising the extensive areas of high flood risk in Derna could motivate their government to better maintain their dams, as well as set up infrastructure in less-accessible areas for shelter and healthcare. 
