# Results and Discussion

In conclusion, the collapse of Derna's dams has caused irreparable damage to Derna, with many of its citizens losing their lives as well as their homes in the catastrophe.

To make sure such an incident does not become a catastrophe in the future, it is imperative to ensure that Derna is well equipped to handle such floods, with proper planning of their future buildings.

With regards to residential or apartment buildings, in the future, these buildings should be built further from the coast. The current concentration of citizens near the coast, as illuminated by the maps, shows the vulnerability of these coastal communities to flood-related hazards. By strategically designing future residential or apartment buildings further inland, urban planners can contribute to a more resilient Derna. This planning seeks to reduce the human and infrastructural toll of flooding, fostering a safer and more sustainable living environment. Moreover, dispersing residential areas away from flood-prone zones aligns with principles of disaster risk reduction, offering a solution to reduce the impact of potential flood events. This new layout of buildings will also lead to a greater cost effectiveness when allocating resources to people affected by future floods. With fewer individuals situated in flood-prone areas, the demand for evacuation resources is likely to diminish, resulting in a more efficient and targeted allocation of emergency response teams, evacuation routes, and relief supplies.

With regards to health facilities and evacuation centres, future facilities and centres should be built at places that are outside flood prone areas, but at the same time, be accessible to people that are within these flood prone areas. In charting the course for future health facilities and evacuation centres, a priority should be assigned to locations that guarantee unimpeded access for individuals residing in flood-prone areas. This placement is designed not only to mitigate the impact of potential floods on the functionality of these facilities but, more importantly, to ensure that residents in high-risk zones have swift and convenient access to healthcare and evacuation services during emergencies. Furthermore, as shown by the accessibility map above, there is a lack of accessibility to those services even at places not near the coastline but are affected by the floods. When building future facilities or centres, priority should be given to better serve these people and provide them with better care in the event of a flood.

Lastly, with regards to other important infrastructure such as water and power plants, future placements of these buildings should take into consideration the slope analysis map shown above. By placing these critical infrastructure at places with higher elevation, it reduces the risk of things such as electricity and fresh water being not available during future crises. Having these important basic necessities in times of disaster could prove very beneficial for the citizens of Derna and can increase their resilience to such disasters.

# **Future considerations**

To broaden the scope of our investigation and foster a more comprehensive call-to-action, several considerations can be made.

Firstly, the adoption of smaller hexagonal sizes for future analysis might prove to be more valuable. Given Derna's relatively compact size as a town, employing smaller hexagons offers increased precision in capturing the small details of the population distribution and flood risk, contributing to a more accurate and detailed assessment.

Secondly, the use of satellite imagery and field data should be used to better increase the precision of determining whether a building is considered a residential or apartment building. By having greater accuracy in determining building type, we are then able to get a better gauge of Derna's population density per hexagon. This would allow for more precise and effective planning of future resources.

Lastly, when considering locations of future health facilities, the north-west part of Derna should be given some consideration. Currently, the people at the north-west region of Derna lack access to these facilities and would benefit from having a health facility in the form of a clinic or hospital being built there.
